./mainall 1 1 SPSCLatencyResults
./mainall 1 2 SPSCLatencyResults
./mainall 1 4 SPSCLatencyResults
./mainall 1 6 SPSCLatencyResults
./mainall 1 8 SPSCLatencyResults
./mainall 1 12 SPSCLatencyResults
./mainall 1 16 SPSCLatencyResults
./mainall 1 24 SPSCLatencyResults
./mainall 1 32 SPSCLatencyResults
./mainall 1 48 SPSCLatencyResults
./mainall 1 57 SPSCLatencyResults
./mainall 1 64 SPSCLatencyResults
./mainall 1 96 SPSCLatencyResults
./mainall 1 114 SPSCLatencyResults
./mainall 1 192 SPSCLatencyResults
./mainall 1 228 SPSCLatencyResults
./mainall 1 384 SPSCLatencyResults
./mainall 1 456 SPSCLatencyResults
./mainall 1 768 SPSCLatencyResults
./mainall 1 912 SPSCLatencyResults
./mainall 1 1024 SPSCLatencyResults

./mainth 1 1 SPSCThroughputResults
./mainth 1 2 SPSCThroughputResults
./mainth 1 4 SPSCThroughputResults
./mainth 1 6 SPSCThroughputResults
./mainth 1 8 SPSCThroughputResults
./mainth 1 12 SPSCThroughputResults
./mainth 1 16 SPSCThroughputResults
./mainth 1 24 SPSCThroughputResults
./mainth 1 32 SPSCThroughputResults
./mainth 1 48 SPSCThroughputResults
./mainth 1 57 SPSCThroughputResults
./mainth 1 64 SPSCThroughputResults
./mainth 1 96 SPSCThroughputResults
./mainth 1 114 SPSCThroughputResults
./mainth 1 192 SPSCThroughputResults
./mainth 1 228 SPSCThroughputResults
./mainth 1 384 SPSCThroughputResults
./mainth 1 456 SPSCThroughputResults
./mainth 1 768 SPSCThroughputResults
./mainth 1 912 SPSCThroughputResults
./mainth 1 1024 SPSCThroughputResults

./mainallmpmc 4 1 MPMCLatencyResults
./mainallmpmc 4 2 MPMCLatencyResults
./mainallmpmc 4 4 MPMCLatencyResults
./mainallmpmc 4 6 MPMCLatencyResults
./mainallmpmc 4 8 MPMCLatencyResults
./mainallmpmc 4 12 MPMCLatencyResults
./mainallmpmc 4 16 MPMCLatencyResults
./mainallmpmc 4 24 MPMCLatencyResults
./mainallmpmc 4 32 MPMCLatencyResults
./mainallmpmc 4 48 MPMCLatencyResults
./mainallmpmc 4 57 MPMCLatencyResults
./mainallmpmc 4 64 MPMCLatencyResults
./mainallmpmc 4 96 MPMCLatencyResults
./mainallmpmc 4 114 MPMCLatencyResults
./mainallmpmc 4 192 MPMCLatencyResults
./mainallmpmc 4 228 MPMCLatencyResults
./mainallmpmc 4 384 MPMCLatencyResults
./mainallmpmc 4 456 MPMCLatencyResults
./mainallmpmc 4 768 MPMCLatencyResults
./mainallmpmc 4 912 MPMCLatencyResults
./mainallmpmc 4 1024 MPMCLatencyResults

./mainthmpmc 4 1 MPMCThroughputResults
./mainthmpmc 4 2 MPMCThroughputResults
./mainthmpmc 4 4 MPMCThroughputResults
./mainthmpmc 4 6 MPMCThroughputResults
./mainthmpmc 4 8 MPMCThroughputResults
./mainthmpmc 4 12 MPMCThroughputResults
./mainthmpmc 4 16 MPMCThroughputResults
./mainthmpmc 4 24 MPMCThroughputResults
./mainthmpmc 4 32 MPMCThroughputResults
./mainthmpmc 4 48 MPMCThroughputResults
./mainthmpmc 4 57 MPMCThroughputResults
./mainthmpmc 4 64 MPMCThroughputResults
./mainthmpmc 4 96 MPMCThroughputResults
./mainthmpmc 4 114 MPMCThroughputResults
./mainthmpmc 4 192 MPMCThroughputResults
./mainthmpmc 4 228 MPMCThroughputResults
./mainthmpmc 4 384 MPMCThroughputResults
./mainthmpmc 4 456 MPMCThroughputResults
./mainthmpmc 4 768 MPMCThroughputResults
./mainthmpmc 4 912 MPMCThroughputResults
./mainthmpmc 4 1024 MPMCThroughputResults
