#make clean all
#./main 1 1 SPSCLatencyResults
#./main 1 2 SPSCLatencyResults
#./main 1 4 SPSCLatencyResults
#./main 1 6 SPSCLatencyResults
#./main 1 8 SPSCLatencyResults
#./main 1 12 SPSCLatencyResults
#./main 1 16 SPSCLatencyResults
#./main 1 24 SPSCLatencyResults
#./main 1 32 SPSCLatencyResults
#./main 1 48 SPSCLatencyResults
#./main 1 64 SPSCLatencyResults
#./main 1 96 SPSCLatencyResults
#./main 1 114 SPSCLatencyResults
#./main 1 192 SPSCLatencyResults
#./main 1 228 SPSCLatencyResults
#./main 1 384 SPSCLatencyResults
#./main 1 456 SPSCLatencyResults
#./main 1 768 SPSCLatencyResults
#./main 1 912 SPSCLatencyResults
#./main 1 1024 SPSCLatencyResults

#make clean th
#./main 1 1 SPSCThroughputResults
#./main 1 2 SPSCThroughputResults
#./main 1 4 SPSCThroughputResults
#./main 1 6 SPSCThroughputResults
#./main 1 8 SPSCThroughputResults
#./main 1 12 SPSCThroughputResults
#./main 1 16 SPSCThroughputResults
#./main 1 24 SPSCThroughputResults
#./main 1 32 SPSCThroughputResults
#./main 1 48 SPSCThroughputResults
#./main 1 64 SPSCThroughputResults
#./main 1 96 SPSCThroughputResults
#./main 1 114 SPSCThroughputResults
#./main 1 192 SPSCThroughputResults
#./main 1 228 SPSCThroughputResults
#./main 1 384 SPSCThroughputResults
#./main 1 456 SPSCThroughputResults
#./main 1 768 SPSCThroughputResults
#./main 1 912 SPSCThroughputResults
#./main 1 1024 SPSCThroughputResults

make clean allmpmc
./main 4 1 MPMCLatencyResults
./main 4 2 MPMCLatencyResults
./main 4 4 MPMCLatencyResults
./main 4 6 MPMCLatencyResults
./main 4 8 MPMCLatencyResults
./main 4 12 MPMCLatencyResults
./main 4 16 MPMCLatencyResults
./main 4 24 MPMCLatencyResults
./main 4 32 MPMCLatencyResults
./main 4 48 MPMCLatencyResults
./main 4 64 MPMCLatencyResults
./main 4 96 MPMCLatencyResults
./main 4 114 MPMCLatencyResults
./main 4 192 MPMCLatencyResults
./main 4 228 MPMCLatencyResults
./main 4 384 MPMCLatencyResults
./main 4 456 MPMCLatencyResults
./main 4 768 MPMCLatencyResults
./main 4 912 MPMCLatencyResults
./main 4 1024 MPMCLatencyResults

make clean thmpmc
./main 4 1 MPMCThroughputResults
./main 4 2 MPMCThroughputResults
./main 4 4 MPMCThroughputResults
./main 4 6 MPMCThroughputResults
./main 4 8 MPMCThroughputResults
./main 4 12 MPMCThroughputResults
./main 4 16 MPMCThroughputResults
./main 4 24 MPMCThroughputResults
./main 4 32 MPMCThroughputResults
./main 4 48 MPMCThroughputResults
./main 4 64 MPMCThroughputResults
./main 4 96 MPMCThroughputResults
./main 4 114 MPMCThroughputResults
./main 4 192 MPMCThroughputResults
./main 4 228 MPMCThroughputResults
./main 4 384 MPMCThroughputResults
./main 4 456 MPMCThroughputResults
./main 4 768 MPMCThroughputResults
./main 4 912 MPMCThroughputResults
./main 4 1024 MPMCThroughputResults